/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nlu.QLDN3.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the NhanVien service. Represents a row in the &quot;QLDN_NhanVien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nlu.QLDN3.db.model.impl.NhanVienModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nlu.QLDN3.db.model.impl.NhanVienImpl}.
 * </p>
 *
 * @author ThanhToa-PC
 * @see NhanVien
 * @see com.nlu.QLDN3.db.model.impl.NhanVienImpl
 * @see com.nlu.QLDN3.db.model.impl.NhanVienModelImpl
 * @generated
 */
public interface NhanVienModel extends BaseModel<NhanVien> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nhan vien model instance should use the {@link NhanVien} interface instead.
	 */

	/**
	 * Returns the primary key of this nhan vien.
	 *
	 * @return the primary key of this nhan vien
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this nhan vien.
	 *
	 * @param primaryKey the primary key of this nhan vien
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ma nhan vien of this nhan vien.
	 *
	 * @return the ma nhan vien of this nhan vien
	 */
	@AutoEscape
	public String getMaNhanVien();

	/**
	 * Sets the ma nhan vien of this nhan vien.
	 *
	 * @param maNhanVien the ma nhan vien of this nhan vien
	 */
	public void setMaNhanVien(String maNhanVien);

	/**
	 * Returns the ma cong ty of this nhan vien.
	 *
	 * @return the ma cong ty of this nhan vien
	 */
	@AutoEscape
	public String getMaCongTy();

	/**
	 * Sets the ma cong ty of this nhan vien.
	 *
	 * @param maCongTy the ma cong ty of this nhan vien
	 */
	public void setMaCongTy(String maCongTy);

	/**
	 * Returns the ten nhan vien of this nhan vien.
	 *
	 * @return the ten nhan vien of this nhan vien
	 */
	@AutoEscape
	public String getTenNhanVien();

	/**
	 * Sets the ten nhan vien of this nhan vien.
	 *
	 * @param tenNhanVien the ten nhan vien of this nhan vien
	 */
	public void setTenNhanVien(String tenNhanVien);

	/**
	 * Returns the ngay sinh of this nhan vien.
	 *
	 * @return the ngay sinh of this nhan vien
	 */
	@AutoEscape
	public String getNgaySinh();

	/**
	 * Sets the ngay sinh of this nhan vien.
	 *
	 * @param ngaySinh the ngay sinh of this nhan vien
	 */
	public void setNgaySinh(String ngaySinh);

	/**
	 * Returns the gioi tinh of this nhan vien.
	 *
	 * @return the gioi tinh of this nhan vien
	 */
	@AutoEscape
	public String getGioiTinh();

	/**
	 * Sets the gioi tinh of this nhan vien.
	 *
	 * @param gioiTinh the gioi tinh of this nhan vien
	 */
	public void setGioiTinh(String gioiTinh);

	/**
	 * Returns the s d t of this nhan vien.
	 *
	 * @return the s d t of this nhan vien
	 */
	@AutoEscape
	public String getSDT();

	/**
	 * Sets the s d t of this nhan vien.
	 *
	 * @param SDT the s d t of this nhan vien
	 */
	public void setSDT(String SDT);

	/**
	 * Returns the ngay vao lam of this nhan vien.
	 *
	 * @return the ngay vao lam of this nhan vien
	 */
	@AutoEscape
	public String getNgayVaoLam();

	/**
	 * Sets the ngay vao lam of this nhan vien.
	 *
	 * @param ngayVaoLam the ngay vao lam of this nhan vien
	 */
	public void setNgayVaoLam(String ngayVaoLam);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.nlu.QLDN3.db.model.NhanVien nhanVien);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.nlu.QLDN3.db.model.NhanVien> toCacheModel();

	@Override
	public com.nlu.QLDN3.db.model.NhanVien toEscapedModel();

	@Override
	public com.nlu.QLDN3.db.model.NhanVien toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}