/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nlu.doanhnghiep.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KhuVuc service. Represents a row in the &quot;nlu_KhuVuc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nlu.doanhnghiep.model.impl.KhuVucModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nlu.doanhnghiep.model.impl.KhuVucImpl}.
 * </p>
 *
 * @author Anh ba khia
 * @see KhuVuc
 * @see com.nlu.doanhnghiep.model.impl.KhuVucImpl
 * @see com.nlu.doanhnghiep.model.impl.KhuVucModelImpl
 * @generated
 */
public interface KhuVucModel extends BaseModel<KhuVuc> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a khu vuc model instance should use the {@link KhuVuc} interface instead.
	 */

	/**
	 * Returns the primary key of this khu vuc.
	 *
	 * @return the primary key of this khu vuc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this khu vuc.
	 *
	 * @param primaryKey the primary key of this khu vuc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the kvid of this khu vuc.
	 *
	 * @return the kvid of this khu vuc
	 */
	public long getKvid();

	/**
	 * Sets the kvid of this khu vuc.
	 *
	 * @param kvid the kvid of this khu vuc
	 */
	public void setKvid(long kvid);

	/**
	 * Returns the user ID of this khu vuc.
	 *
	 * @return the user ID of this khu vuc
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this khu vuc.
	 *
	 * @param userId the user ID of this khu vuc
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this khu vuc.
	 *
	 * @return the user uuid of this khu vuc
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this khu vuc.
	 *
	 * @param userUuid the user uuid of this khu vuc
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the ngay add of this khu vuc.
	 *
	 * @return the ngay add of this khu vuc
	 */
	public Date getNgayAdd();

	/**
	 * Sets the ngay add of this khu vuc.
	 *
	 * @param ngayAdd the ngay add of this khu vuc
	 */
	public void setNgayAdd(Date ngayAdd);

	/**
	 * Returns the ten kv of this khu vuc.
	 *
	 * @return the ten kv of this khu vuc
	 */
	@AutoEscape
	public String getTenKv();

	/**
	 * Sets the ten kv of this khu vuc.
	 *
	 * @param tenKv the ten kv of this khu vuc
	 */
	public void setTenKv(String tenKv);

	/**
	 * Returns the dia chi of this khu vuc.
	 *
	 * @return the dia chi of this khu vuc
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this khu vuc.
	 *
	 * @param diaChi the dia chi of this khu vuc
	 */
	public void setDiaChi(String diaChi);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.nlu.doanhnghiep.model.KhuVuc khuVuc);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.nlu.doanhnghiep.model.KhuVuc> toCacheModel();

	@Override
	public com.nlu.doanhnghiep.model.KhuVuc toEscapedModel();

	@Override
	public com.nlu.doanhnghiep.model.KhuVuc toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}